uint64 request_timestamp	# time since system start (microseconds)
bool request_collisionavoidance
---
uint64 response_timestamp	# time since system start (microseconds)
bool response_collisionavoidance