#!/bin/sh
#
# @name QTR Inha
#
# @type QTR HEXA 6
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set-default MC_YAWRATE_I 0.02
param set-default MC_YAWRATE_K 1.0
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAW_P 1.0

set MIXER hexa_qtr